# experiment configs
experiment_name: "cvim09_03"

# basic configs
batchsize: 20
n_epochs: 40
seed: 0

video_length: 16
image_size: 64

log_dir: "result/isogd"
tensorboard_dir: "result/isogd/runs"

# interval
log_interval:         100
log_samples_interval: 5000
snapshot_interval:    5000
evaluation_interval:  60000

# dataset configs
dataset: 
  name: "isogd"
  path: "data/isogd"
  n_workers: 4
  number_limit: -1

# model configs
gen:
  dim_z_content: 40
  dim_z_motion: 10
  dim_z_color: 10
  optimizer:
    lr: 0.0002
    decay: 0.00001
idis: 
  # TODO: noise sigma schedule
  use_noise: True
  noise_sigma: 0.1
  ndf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001
vdis: 
  use_noise: True
  noise_sigma: 0.1
  ndf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001
